---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelapp-webapp
  namespace: tamr-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: otelapp-webapp
  template:
    metadata:
      labels:
        app: otelapp-webapp
    spec:
      containers:
      - name: otelapp
        image: 'us-docker.pkg.dev/tamr-docker/ops/otelapp:0.2.0'
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: OTEL_EXPORTER
          value: zipkin
        - name: OTEL_EXPORTER_ZIPKIN_SERVICE_NAME
          value: otelapp
        - name: SIGNALFX_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
          value: 'http://$(SIGNALFX_AGENT_HOST):9080/v1/trace'
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30



