---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelapp-webapp
  namespace: tamr-system
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: otelapp-webapp
  template:
    metadata:
      labels:
        app: otelapp-webapp
    spec:
      containers:
      - image: us-docker.pkg.dev/tamr-docker/ops/otelapp:0.1.0
        name: otelapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: somekey
          value: somevalue
      # - name: http-requests
      #   imagePullPolicy: IfNotPresent
      #   image: us-docker.pkg.dev/tamr-docker/ops/otelapp:0.1.0
      #   command: ['sh', '-c', 'while true; do curl http://localhost:8080/ && sleep 0.1 && echo ""; done;']
      #   resources:
      #     limits:
      #       cpu: 1000m
      #       memory: 1024Mi
      #     requests:
      #       cpu: 1000m
      #       memory: 512Mi
